language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: pwoolvett
  password:
    secure: RiAGbgVDGoUOl2kaH/+hbScLXo/bEU4wabJ1HX+Ibe45Z/Dsa6/RcF/uF//8/0vJhI7hBhEpJJSE/MFB+H38n+R0rfVdbd7y4aB568AAKfgFG+OVChPjx6wYG82ziRK7jXkmnxRxm0acnGBnhQB1UXLNRGVUK8j26K00BBh0IlyiHvYDh/8SNmDslyc16QSs/LF1m8Q6rS1erMAzwqmKNmpvP1DFFmRPCejAlORXeqZC/ARDvGTr1J3kUlbS3Pf53vdYCQgVAWPwvxxk7dZuSGyV8z45xAtkUJCj4R01NIcZ6GB8e0aNWJCyl8DbkTDVryDuCrpU8VtnE1xVOOwmP8SmdjA9wAmcZ/cUUaxrrISluhfmuswF6cH4rcR5CibRpjx/+VQDGbc/Gb8SEHVcEtTFASx7DNZWCzxbhl+6T3Lw4/7BHq8T77L/gYVRPTaW0smo8wlNJYupe/z70GIaY8lhsVQ5InB7Hw8ykc1GK1vR4yHQzdznRL0j8I8GMpNXRWRsMSwP2R0v9tmaiWUIrGLKAG9BEYjbmk4VhrV+m7MJogvrIYpOKbqeO67LNe2HsJCcmngvKglOLfIj7VPm7/Tkg4I+dhIgr/pV6gyCyUOlxp06XgsJKHizrU9YmNpznePS9zL8zPZgAKJ92UgVpARYNBxq3tBRllP879psbBY=
  on:
    branch: master
    repo: pwoolvett/waluigi
    python: 3.6
