language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: pwoolvett
  password:
    secure: aTe3cQXvv/HH0OEjuMFkcleQ6bfjuLxsaHbO6+RXOOLZaoZdoaUh/pv13oJ7le7axygztY7u3V1QHJp19kdfGZVtPYd5n5f1ThtPuGuuNFg6W7YkxE2b+I+gjtSkIR1V8X1YOQLPAj6WHxo9zZTKw0BVuyaC8kErfCOXOmKs7QXp9OsJaQfQqxE6XKmnwSBeWT2AYmEbYnFfG3XJ7aqknA5w/JJLKZrvNcmcisPimSYWZYHF9IvBKXCkHUH2DiLDbIHG8EtE+U81TkXgyJO7XOlt26xgJtyAYyE8Ick0Nf9FAeOJlFK7YPq4WqxdIvoOPArreNgmuOMDLhU0d7zg29wsFGblxJknStatTT8pXnQ2bHy0FmxBmVFlAlsUx/gFFYFHnTXpBDPl0e9lZPOW6ijo9nDPRD8DM4HZTcBH5dbuxjizPGpj1u1Y+BG3yCWfeuWR5sm+At2+jMXyaiTR8DBeN2deA2jpnch7T0uAN1nYzzjPTqPuv3tl0SCRtXWhY3h5HK2nEKrka3i8r7yzmUEtvkaG6sXRwmtUIy+zAY0nbS0KckPXUGZG4Nnh2ataVCNIBvsiQb/jTs5R9LmkZU5JrSL8RMIujFHOLIyNKjjrwxJjMRgQsvqcyF6qX4R4G1dhxmpO2Hcp5/nAUxVPpBL12jfwSfDmvcQmDv3e6No=
  on:
    branch: master
    repo: pwoolvett/waluigi
    python: 3.6
